baseURL = "https://blog.almubaireek.com/"
title = "Saad ALMubaireek – EE Projects & Experiments"
theme = "PaperMod"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

[languages]

  [languages.en]
    languageName = "English"
    weight = 1
    contentDir = "content/en"

    [languages.en.params]
      heroTitle = "Exploring Electrical Engineering, One Quirky Project at a Time"
      heroSubTitle = "PCB design, 3D enclosures, and microcontroller boards"

    [languages.en.menu]

      [[languages.en.menu.main]]
        name = "Home"
        identifier = "nav-home"
        url = "/"
        weight = 1

      [[languages.en.menu.main]]
        name = "Projects"
        identifier = "nav-projects"
        url = "/projects/"
        weight = 2

      [[languages.en.menu.main]]
        name = "Personal projects"
        identifier = "nav-personal-projects"
        url = "/personal-projects/"
        weight = 3

      [[languages.en.menu.main]]
        name = "Eco-Drive"
        identifier = "nav-eco-drive"
        url = "/projects/eco-drive/"
        weight = 4

      [[languages.en.menu.main]]
        name = "Smart IoT Electric Extension"
        identifier = "nav-smart-iot-electric-extension"
        url = "/projects/smart-iot-electric-extension/"
        weight = 5

      [[languages.en.menu.main]]
        name = "Tutorials"
        identifier = "nav-tutorials"
        url = "/tutorials/"
        weight = 6

      [[languages.en.menu.main]]
        name = "3D Design"
        identifier = "nav-3d-design"
        url = "/3d-design/"
        weight = 7

      [[languages.en.menu.main]]
        name = "About"
        identifier = "nav-about"
        url = "/about/"
        weight = 8

      [[languages.en.menu.main]]
        name = "Contact"
        identifier = "nav-contact"
        url = "/contact/"
        weight = 9

[[languages.en.menu.main]]
  name = "TypeCoach"
  identifier = "nav-typecoach"
  url = "/en/typecoach/"
  weight = 10

[pagination]
  pagerSize = 5

[params]
  defaultTheme = "auto"
  showSocial = true
  showSocialEmpty = false
  ShowReadingTime = false
  ShowBreadCrumbs = true
  ShowShareButtons = true
  ShareButtons = ["linkedin", "whatsapp", "email"]
  ShowPostNavLinks = true
  ShowCodeCopyButtons = true
  heroEnable = true
  heroImage = "/images/hero-banner.jpg"
  sidebarShow = true
  sidebarWidgets = ["search", "categories", "social", "downloads"]
  ShowLangSwitch = false

[params.social]
  github = "https://github.com/s2qx"
  linkedin = "https://www.linkedin.com/in/saad-khaild-almubaireek"
  whatsapp = "https://wa.me/547252287"
  email = "mailto:saad@almubaireek.com"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true